{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terrastrata.serviceAccountName" . }}
  labels:
    {{- include "terrastrata.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
